---

- hosts: myhosts
  name: Manage System Power - Graceful shutdown
  gather_facts: False

  tasks:

  - name: Graceful system power shutdown
    local_action: >
       redfish category=System command=PowerGracefulShutdown baseuri={{baseuri}}
       user={{user}} password={{password}}
