---
- hosts: myhosts
  name: Get BIOS boot order
  gather_facts: False

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml type=BiosBootOrder
    tags: getbootorder

  - name: Get device boot order
    local_action: >
       redfish category=System command=GetBiosBootOrder baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
    ignore_errors: yes
    tags: getbootorder

  - name: Copy boot order to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
    tags: getbootorder
