---
- hosts: myhosts
  name: Set boot mode to UEFI and reboot
  gather_facts: False

  tasks:

  - name: Set BootMode to UEFI
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=BootMode bios_attr_value=Uefi
    tags: bootmodeuefi
    ignore_errors: yes

  - name: Create config job - reboot
    local_action: >
      redfish category=System command=CreateBiosConfigJob baseuri={{baseuri}}
      user={{user}} password={{password}}
    tags: createbiosconfigjob
    ignore_errors: yes
