---
#
# Playbook to test ansible variables, tasks
# and other things without using a full-blown
# playbook.
#

- hosts: all:!switches:!oobservers
  remote_user: root
  tasks: []

- hosts: test
  remote_user: root
  roles:
    - { role: test }
