---
- hosts: myhosts
  name: CPU Inventory
  gather_facts: False

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml type=CpuInventory

  - name: Get CPU Inventory
    local_action: >
       redfish category=Inventory command=GetCpuInventory baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
    ignore_errors: yes

  - name: Copy information to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
