---
- gather_facts: False
  name: check for racadm
  vars:
    untouchables: mgmt-foreman.example.com
  hosts: all:!{{untouchables}}
  tasks:

# Wipe raid controller
    - name: racadm resetcfg
      raw: racadm raid resetconfig:RAID.Integrated.1-1
      args:
        executable: ''
      register: result_resetcfg
    - debug: var=result_resetcfg

# Delete the jobqueue to we can search it reliably later
    - name: racadm jobqueue delete
      raw: racadm jobqueue delete --all
      args:
        executable: ''
      register: result_jobqueue
    - debug: var=result_jobqueue

# Ensure we are starting with a powered down system
    - name: racadm serveraction powerdown
      raw: racadm serveraction powerdown
      args:
        executable: ''
      register: result_powerdown
    - debug: var=result_powerdown

# Commit the changes to the raid controller
    - name: racadm raid reconfigure powercycle
      raw: racadm jobqueue create RAID.Integrated.1-1 -s TIME_NOW  -r pwrcycle
      args:
        executable: ''
      register: result_pwrcycle
    - debug: var=result_pwrcycle

# Now wait for the jobqueue to finish
    - name: racadm check complete
      raw: racadm jobqueue view
      args:
        executable: ''
      register: result_check_complete
      until: result_check_complete.stdout.find("Status=Completed") != -1 and result_check_complete.stdout.find("Status=Running") == -1
      retries: 2000
      delay: 10
    - debug: var=result_check_complete

# Turn off the server
    - name: racadm serveraction powerdown
      raw: racadm serveraction powerdown
      args:
        executable: ''
      register: result_powerdown
    - debug: var=result_powerdown

# Delete the jobqueue to we can search it reliably later
    - name: racadm jobqueue delete
      raw: racadm jobqueue delete --all
      args:
        executable: ''
      register: result_jobqueue
    - debug: var=result_jobqueue

# setup hardware raid across first two drives
    - name: racadm setup vdisk
      raw: racadm raid createvd:RAID.Integrated.1-1 -rl r1 -pdkey:Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1,Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1
      args:
        executable: ''
      register: result_vdisk_setup
    - debug: var=result_vdisk_setup

# Commit the changes to the raid controller
    - name: racadm raid reconfigure powercycle
      raw: racadm jobqueue create RAID.Integrated.1-1 -s TIME_NOW  -r pwrcycle
      args:
        executable: ''
      register: result_pwrcycle
    - debug: var=result_pwrcycle

# Now wait for the jobqueue to finish
    - name: racadm check complete
      raw: racadm jobqueue view
      args:
        executable: ''
      register: result_check_complete
      until: result_check_complete.stdout.find("Status=Completed") != -1 and result_check_complete.stdout.find("Status=Running") == -1
      retries: 2000
      delay: 10
    - debug: var=result_check_complete

# Turn off the server
    - name: racadm serveraction powerdown
      raw: racadm serveraction powerdown
      args:
        executable: ''
      register: result_powerdown
    - debug: var=result_powerdown


