---
- gather_facts: False
  name: set root password
  hosts: all
  tasks:
    - name: set root password to supplied value
      raw: racadm set iDRAC.Users.2.Password {{ root_password }}
      args:
        executable: ''
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    - debug: var=result
