--- # Testing
- hosts: idrac-1
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: arp -- display the networking ARP table
      raw: racadm arp 
      register: arp
    - debug: var=arp
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ arp.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/arp/{{ inventory_hostname }}-arp-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"