--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: clearasrscreen -- clear the last ASR (crash) screen
      raw: racadm clearasrscreen
      register: clearasrscreen
    - debug: var=clearasrscreen
    - local_action: copy content={{ clearasrscreen.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/clearasrscreen/{{ inventory_hostname }}-cas.txt
