--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: clearasrscreen -- clear the last ASR (crash) screen
      raw: racadm clearasrscreen
      register: clearasrscreen
    - debug: var=clearasrscreen
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/clearasrscreen/{{ inventory_hostname }}-clearasrscreen-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ clearasrscreen.stdout_lines }}"
