--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: id
      prompt: What is the ID of the session you want to close?
      private: no
  tasks:
    - name: CLose sessions of certain ID
      raw: racadm closessn -i {{ id }}
      register: closessnID
    - debug: var=closessnID
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ closessnID.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/closessn/{{ inventory_hostname }}-closessnID-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
