--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: user
      prompt: Who is the user of the session you want to close?
      private: no
  tasks:
    - name: CLose sessions of certain user
      raw: racadm closessn -i {{ user }}
      register: closessnUser
    - debug: var=closessnUser
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ closessnUser.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/closessn/{{ inventory_hostname }}-closessnUser-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
