.--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: clrraclog -- clear the RAC log
      raw: racadm clrraclog
      register: clrraclog
    - debug: var=clrraclog
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ clrraclog.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/clrraclog/{{ inventory_hostname }}-crl-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
