.--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: clrraclog -- clear the RAC log
      raw: racadm clrraclog
      register: clrraclog
    - debug: var=clrraclog
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/clrraclog/{{ inventory_hostname }}-clrraclog-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ clrraclog.stdout_lines }}"
