--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: clrsel -- clear the System Event Log (SEL)
      raw: racadm clrsel
      register: clrsel
    - debug: var=clrsel
    - local_action: copy content={{ clrsel.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/clrsel/{{ inventory_hostname }}-clrsel.txt
