--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: {{ command }}
      prompt: What command do you want to give?
      private: no
  tasks:
    - name: Performing command on iDRAC
      raw: {{ command }}
      register: iDRAC
    - debug: var=iDRAC
    - local_action: copy content={{ iDRAC.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/iDRAC/{{ inventory_hostname }}-iDRAC.txt
