--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: {{ command }}
      prompt: What command do you want to give?
      private: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/iDRAC/{{ inventory_hostname }}
      delegate_to: localhost
    - name: Performing command on iDRAC
      raw: {{ command }}
      register: iDRAC
    - debug: var=iDRAC
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/iDRAC/{{ inventory_hostname }}/iDRAC-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ iDRAC.stdout_lines }}"
