--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: coredumpdelete -- display the last RAC coredump
      raw: racadm coredumpdelete
      register: coredumpdelete
    - debug: var=coredumpdelete
    - local_action: copy content={{ coredumpdelete.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/coredumpdelete/{{ inventory_hostname }}-coredumpdelete.txt
