--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: coredump -- display the last RAC coredump
      raw: racadm coredump
      register: coredump
    - debug: var=coredump
    - local_action: copy content={{ coredump.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/coredump/{{ inventory_hostname }}-coredump.txt
