--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: coredump -- display the last RAC coredump
      raw: racadm coredump
      register: coredump
    - debug: var=coredump
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ coredump.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/coredump/{{ inventory_hostname }}-coredump-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
