--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/coredump/{{ inventory_hostname }}
      delegate_to: localhost
    - name: coredump -- display the last RAC coredump
      raw: racadm coredump
      register: coredump
    - debug: var=coredump
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/coredump/{{ inventory_hostname }}/coredump-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ coredump.stdout_lines }}"
