--- # Testing
- hosts: idrac-1
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars:
    file: "{{ lookup('file', '/root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/nonIndexList.txt') }}"
  tasks:
    - name: getconfig -- display individual RAC configuration properties
      raw: racadm getconfig -g {{ item }}
      with_items: "{{ file }}"
      register: loop
    - debug: var=loop
    - name: Copy to config files
      shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/{{ item[0].item }}-config.txt
      delegate_to: localhost
      with_subelements: 
        - "{{ loop.results }}"
        - "stdout_lines"