--- # Testing
#
- hosts: idrac-1
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}
      delegate_to: localhost
    - name: delete previous config logs
      shell: rm /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/*
      delegate_to: localhost
    - name: getconfig -- display RAC configuration properties
      raw: racadm getconfig -h
      register: racadm_config
    - debug: var=racadm_config
    - name: copy to configList
      shell: echo '{{ item }}' >> /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/configList.txt
      delegate_to: localhost
      with_items: "{{ racadm_config.stdout_lines }}"
    - name: copy to indexList
      shell: cd /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/ | grep ERROR * | grep -o "^[^-]*" > indexList.txt
      delegate_to: localhost
    - name: copy to nonIndexList
      shell: cd /root/ansible-idrac/auto-idrac/output/configs/{{ inventory_hostname }}/ | grep -vf indexList.txt configList.txt > nonIndexList.txt
      delegate_to: localhost
