--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getled -- Get the state of the LED on a module.
      raw: racadm getled
      register: getled
    - debug: var=getled
    - local_action: copy content={{ getled.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/getled/{{ inventory_hostname }}-getled.txt
