--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getled -- Get the state of the LED on a module.
      raw: racadm getled
      register: getled
    - debug: var=getled
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ getled.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/getled/{{ inventory_hostname }}-getled-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
