--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getniccfg -- display current network settings
      raw: racadm getniccfg
      register: nic_config
    - debug: var=nic_config
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ nic_config.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/niccfg/{{ inventory_hostname }}-niccfg-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
