--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getniccfg -- display current network settings
      raw: racadm getniccfg
      register: nic_config
    - debug: var=nic_config
    - local_action: copy content={{ nic_config.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/niccfg/{{ inventory_hostname }}-niccfg.txt
