--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/getniccfg/{{ inventory_hostname }}
      delegate_to: localhost
    - name: getniccfg -- display current network settings
      raw: racadm getniccfg
      register: nic_config
    - debug: var=nic_config
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/getniccfg/{{ inventory_hostname }}/getniccfg-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ niccfg.stdout_lines }}"