--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getractime -- display the current RAC time 
      raw: racadm getractime 
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ ractime.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/ractime/{{ inventory_hostname }}-ractime.txt
