--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getraclog -- display the RAC log
      raw: racadm getraclog
      register: raclog
    - debug: var=raclog
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ raclog.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/raclog/{{ inventory_hostname }}-raclog-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
