--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getsysinfo -- display general RAC and system information
      raw: racadm getsysinfo
      register: system
    - debug: var=system
    - local_action: copy content={{ system.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/system/{{ inventory_hostname }}-sys.txt
