--- # Testing
- hosts: idrac-1
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getsel -- display records from the System Event Log (SEL)
      raw: racadm getsel
      register: sel
    - debug: var=sel
    - name: getractime -- display the current RAC time
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - name: output to file
      shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/sel/{{ inventory_hostname }}-sel-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ sel.stdout_lines }}"
