--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getsel -- display records from the System Event Log (SEL)
      raw: racadm getsel 
      register: sel
    - debug: var=sel
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ sel.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/sel/{{ inventory_hostname }}-sel-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
