--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/system/{{ inventory_hostname }}
      delegate_to: localhost
    - name: getsysinfo -- display general RAC and system information
      raw: racadm getsysinfo
      register: system
    - debug: var=system
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/system/{{ inventory_hostname }}/system-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ system.stdout_lines }}"