--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getssninfo -- display session information
      raw: racadm getssninfo 
      register: ssn
    - debug: var=ssn
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ ssn.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/ssn/{{ inventory_hostname }}-ssn-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/ssn/{{ inventory_hostname }}-ssn-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ ssn.stdout_lines }}"
