--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getsel -- display records from the System Event Log (SEL)
      raw: racadm getsel 
      register: sel
    - debug: var=sel
    - local_action: copy content={{ sel.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/sel/{{ inventory_hostname }}-sel.txt
