--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/tracelog/{{ inventory_hostname }}
      delegate_to: localhost
    - name: gettracelog -- display the RAC diagnostic trace log
      raw: racadm gettracelog 
      register: tracelog
    - debug: var=tracelog
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/tracelog/{{ inventory_hostname }}/tracelog-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ tracelog.stdout_lines }}"