--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: gettracelog -- display the RAC diagnostic trace log
      raw: racadm gettracelog 
      register: tracelog
    - debug: var=tracelog
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ tracelog.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/tracelog/{{ inventory_hostname }}-tracelog-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
