--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getuscversion -- display the current USC version details
      raw: racadm getuscversion 
      register: uscversion
    - debug: var=uscversion
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ uscversion.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/uscversion/{{ inventory_hostname }}-uscversion-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
