--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getversion -- Display the current version details
      raw: racadm getversion
      register: version
    - debug: var=version
    - local_action: copy content={{ version.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/version/{{ inventory_hostname }}-version.txt
