--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: getversion -- Display the current version details
      raw: racadm getversion
      register: version
    - debug: var=version
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ version.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/version/{{ inventory_hostname }}-version-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
