--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: ifconfig -- display network interface information
      raw: racadm ifconfig 
      register: ifconfig
    - debug: var=ifconfig
    - local_action: copy content={{ ifconfig.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/ifconfig/{{ inventory_hostname }}-ifconfig.txt
