--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: ifconfig -- display network interface information
      raw: racadm ifconfig 
      register: ifconfig
    - debug: var=ifconfig
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ ifconfig.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/ifconfig/{{ inventory_hostname }}-ifconfig-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
