--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/netstat/{{ inventory_hostname }}
      delegate_to: localhost
    - name: netstat -- display routing table and network statistics
      raw: racadm netstat
      register: netstat
    - debug: var=netstat
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/netstat/{{ inventory_hostname }}/netstat-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ netstat.stdout_lines }}"