--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: netstat -- display routing table and network statistics
      raw: racadm netstat
      register: netstat
    - debug: var=netstat
    - local_action: copy content={{ netstat.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/netstat/{{ inventory_hostname }}-netstat.txt
