--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ip_address
      prompt: "What IP do you want to ping?"
      private: no
  tasks:
    - name: ping -- send ICMP echo packets on the network
      raw: racadm ping {{ ip_address }}
      register: ping
    - debug: var=ping
    - local_action: copy content={{ ping.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/ping/{{ inventory_hostname }}-ping.txt
