--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ip_address
      prompt: "What IP do you want to ping?"
      private: no
  tasks:
    - name: ping -- send ICMP echo packets on the network
      raw: racadm ping {{ ip_address }}
      register: ping
    - debug: var=ping
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ ping.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/ping/{{ inventory_hostname }}-ping-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
