--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ip_address
      prompt: "What IP do you want to ping?"
      private: no
  tasks:
    - name: ping6 -- send ICMP echo packets on the network
      raw: racadm ping6 {{ ip_address }}
      register: ping6
    - debug: var=ping6
    - local_action: copy content={{ ping6.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/ping6/{{ inventory_hostname }}-ping6.txt
