--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ip_address
      prompt: "What IP do you want to ping?"
      private: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/ping/{{ inventory_hostname }}
      delegate_to: localhost
    - name: ping -- send ICMP echo packets on the network
      raw: racadm ping {{ ip_address }}
      register: ping
    - debug: var=ping
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/ping/{{ inventory_hostname }}/ping-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ ping.stdout_lines }}"