--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: racdump -- display RAC diagnostic information
      raw: racadm racdump
      register: racdump
    - debug: var=racdump
    - local_action: copy content={{ racdump.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/racdump/niccfg/{{ inventory_hostname }}-racdump.txt
