--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/racdump/{{ inventory_hostname }}
      delegate_to: localhost
    - name: racdump -- display RAC diagnostic information
      raw: racadm racdump
      register: racdump
    - debug: var=racdump
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/racdump/{{ inventory_hostname }}/racdump-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ racdump.stdout_lines }}"