--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: racdump -- display RAC diagnostic information
      raw: racadm racdump
      register: racdump
    - debug: var=racdump
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ racdump.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/racdump/niccfg/{{ inventory_hostname }}-racdump-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
