--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: force
      prompt: Do you want to force reset? (Yes or No)
      private: no
      default: No
  tasks:
    - name: racresetcfg -- restore the RAC configuration to factory defaults
      raw: racadm racresetcfg {{ '-f' if force|bool else '' }}
      register: racresetcfg
    - debug: var=racresetcfg
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ racresetcfg.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/racresetcfg/{{ inventory_hostname }}-racresetcfg-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
