--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: user
      prompt: What is the username to access the shared folder?
      private: no
    - name: pass
      prompt: What is the password of the shared folder?
      private: no
    - name: location
      prompt: What is the network location of the ISO image? (Ex. //shrloc/foo.iso)
      private: no
  tasks:
    - name: Make a remote ISO image available to the server
      raw: racadm remoteimage -c -u "{{ user }}" -p "{{ pass }}" -l {{ location }}
      register: riConnect
    - debug: var=riConnect
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ riConnect.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/remoteimage/{{ inventory_hostname }}-riConnect-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
