--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/remoteimage/{{ inventory_hostname }}
      delegate_to: localhost
    - name: display current Remote Image status 
      raw: racadm remoteimage -s
      register: riDisplay
    - debug: var=riDisplay
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/remoteimage/{{ inventory_hostname }}/riDisplay-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ riDisplay.stdout_lines }}"