--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: Disconnect Remote Image 
      raw: racadm remoteimage -d
      register: riDisconnect
    - debug: var=riDisconnect
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ riDisconnect.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/remoteimage/{{ inventory_hostname }}-riDisconnect-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
