--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: display current Remote Image status 
      raw: racadm remoteimage -s
      register: riDisplay
    - debug: var=riDisplay
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ riDisplay.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/remoteimage/{{ inventory_hostname }}-riDisplay-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
