--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: action
      prompt: Choose from the following: powerdown, powerup, powercycle, hardreset, powerstatus
      private: no
      default: powerstatus
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/serveraction/{{ inventory_hostname }}
      delegate_to: localhost
    - name: serveraction -- perform system power management operations
      raw: racadm serveraction {{ action }}
      register: serveraction
    - debug: var=serveraction
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/serveraction/{{ inventory_hostname }}/serveraction-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ serveraction.stdout_lines }}"