--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: action
      prompt: Choose from the following: powerdown, powerup, powercycle, hardreset, powerstatus
      private: no
      default: powerstatus
  tasks:
    - name: serveraction -- perform system power management operations
      raw: racadm serveraction {{ action }}
      register: serveraction
    - debug: var=serveraction
    - local_action: copy content={{ serveraction.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/serveraction/{{ inventory_hostname }}-serveraction.txt
