--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: action
      prompt: Choose from the following: powerdown, powerup, powercycle, hardreset, powerstatus
      private: no
      default: powerstatus
  tasks:
    - name: serveraction -- perform system power management operations
      raw: racadm serveraction {{ action }}
      register: serveraction
    - debug: var=serveraction
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ serveraction.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/serveraction/{{ inventory_hostname }}-serveraction-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
