--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ledstate
      prompt: Blinking (0) or non-blinking (1)
      private: no
      default: 0
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/led/set/{{ inventory_hostname }}
      delegate_to: localhost
    - name: setled -- Set the state of the LED on a module.
      raw: racadm setled -l {{ ledstate }}
      register: ledState
    - debug: var=ledState
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/led/set/{{ inventory_hostname }}/setled-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ ledState.stdout_lines }}"