--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ipv6
      prompt: What is the IPv6 address
      private: no
    - name: prefix
      prompt: What is the prefix length?
      private: no
    - name: gateway
      prompt: What is the IPv6 gateway?
      private: no
  tasks:
    - name: setniccfg -- modify network configuration properties
      raw: racadm setniccfg {{ ipv6 }} {{ prefix }} {{ gateway }}
      register: IPv6
    - debug: var=IPv6
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/setniccfg/{{ inventory_hostname }}-IPv6-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ IPv6.stdout_lines }}"