--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: ipv4
      prompt: What is the IPv4 address
      private: no
    - name: subnet
      prompt: What is the subnet mask?
      private: no
    - name: gateway
      prompt: What is the IPv4 gateway?
      private: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/setniccfg/IPV4/{{ inventory_hostname }}
      delegate_to: localhost
    - name: setniccfg -- modify network configuration properties
      raw: racadm setniccfg {{ ipv4 }} {{ subnet }} {{ gateway }}
      register: IPv4
    - debug: var=IPv4
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/setniccfg/IPv4/{{ inventory_hostname }}/IPv4-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ IPv4.stdout_lines }}"