--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: 
      prompt: 
      private: no
      default: 
    - name: 
      prompt: 
      private: no
      default: No
  tasks:
    - name: 
      raw: racadm 
      register: 
    - debug: var=
    - local_action: copy content={{ .stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output//{{ inventory_hostname }}-.txt
