--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: option
      prompt: Do you want to generate new certificate signing request (0) or display current status of CSR operation (1)?
      private: no
      default:1
  tasks:
    - name: sslcsrgen -- generate a certificate CSR from the RAC
      raw: racadm sslcsrgen {{ '-s' if option|bool else '-g' }}
      register: 
    - debug: var=
    - local_action: copy content={{ .stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output//{{ inventory_hostname }}-.txt
