--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: get
      prompt: Do you want to get the ssl encyrption strength? (Yes or No)
      private: no
      default: Yes
    - name: restart
      prompt: Do you want to restart the webserver? (Yes or No)
      private: no
      default: No
  tasks:
    - name:  sslEncryptionStrengthGet -- Display the SSL Encryption strength.
      raw: racadm sslEncryptionStrength {'get' if get|bool else ''}} {{'--webserverrestart' if restart|bool else ''}}
      register: sslESGet
    - debug: var=sslESGet
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ sslESGet.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/sslEncryptionStrength/{{ inventory_hostname }}-sslESGet.txt
