--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: get
      prompt: Do you want to get the ssl encyrption strength? (Yes or No)
      private: no
      default: Yes
    - name: restart
      prompt: Do you want to restart the webserver? (Yes or No)
      private: no
      default: No
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/sslEncryptionStrength/{{ inventory_hostname }}
      delegate_to: localhost
    - name:  sslEncryptionStrengthGet -- Display the SSL Encryption strength.
      raw: racadm sslEncryptionStrength {'get' if get|bool else ''}} {{'--webserverrestart' if restart|bool else ''}}
      register: sslESGet
    - debug: var=sslESGet
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/sslEncryptionStrength/{{ inventory_hostname }}/sslESGet-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ sslESGet.stdout_lines }}"