--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: sslresetcfg -- generate a new self-signed certificate 
      raw: racadm sslresetcfg
      register: sslresetcfg
    - debug: var=sslresetcfg
    - local_action: copy content={{ sslresetcfg.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/sslresetcfg/{{ inventory_hostname }}-sslresetcfg.txt
