--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: sslresetcfg -- generate a new self-signed certificate 
      raw: racadm sslresetcfg
      register: sslresetcfg
    - debug: var=sslresetcfg
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ sslresetcfg.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/sslresetcfg/{{ inventory_hostname }}-sslresetcfg-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
