--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/sslresetcfg/{{ inventory_hostname }}
      delegate_to: localhost
    - name: sslresetcfg -- generate a new self-signed certificate 
      raw: racadm sslresetcfg
      register: sslresetcfg
    - debug: var=sslresetcfg
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/sslresetcfg/{{ inventory_hostname }}/sslresetcfg-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ sslresetcfg.stdout_lines }}"