--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: index
      prompt: What is the index of the RAC SNMP trap notification you want to test? (Only index values 1 - 4 are permitted)
      private: no
  tasks:
    - name: testtrap -- test RAC SNMP trap notifications
      raw: racadm testtrap -i {{ index }}
      register: testtrap
    - debug: var=testtrap
    - local_action: copy content={{ testtrap.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/testtrap/{{ inventory_hostname }}-testtrap.txt
