--- # Testing
- hosts: local
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: options
      prompt: This (0) or that (1)
      private: no
      default: 1
  tasks:
    - name: racreset -- perform a RAC reset operation
      shell: echo {{ 'that' if options|bool else 'this' }}
      register: test
    - debug: var=test
