--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: index
      prompt: What is the index of the email alert you want to test? (Only index values 1 - 4 are permitted)
      private: no
  tasks:
    - name: testemail -- test RAC e-mail notifications
      raw: racadm testemail -i {{ index }}
      register: testemail
    - debug: var=testemail
    - local_action: copy content={{ testemail.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/testemail/{{ inventory_hostname }}-testemail.txt
