--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  vars_prompt:
    - name: option
      prompt: What profile number do you want to pick?  < 1= KMS Profile group 1, 2=KMS Profile group 2 >
      private: no
      default: 1
  tasks:
    - name: make directory if not present
      shell: mkdir -p /root/ansible-idrac/auto-idrac/output/testkmsconnectivity/{{ inventory_hostname }}
      delegate_to: localhost
    - name: testkmsconnectivity -- test KMSConnectivity
      raw: racadm testkmsconnectivity -p {{ option }}
      register: testkmsconnectivity
    - debug: var=testkmsconnectivity
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - shell: echo '{{ item[1] }}' >> /root/ansible-idrac/auto-idrac/output/testkmsconnectivity/{{ inventory_hostname }}/testkmsconnectivity-{{ item[0] }}.txt
      delegate_to: localhost
      with_nested:
       - "{{ ractime.stdout_lines }}"
       - "{{ testkmsconnectivity.stdout_lines }}"