--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: gettracelog -- display the RAC diagnostic trace log
      raw: racadm gettracelog 
      register: tracelog
    - debug: var=tracelog
    - local_action: copy content={{ tracelog.stdout_lines }} dest=/root/ansible-idrac/idrac-auto/output/tracelog/{{ inventory_hostname }}-tracelog.txt
