--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: vmdisconnect -- disconnect Virtual Media connections 
      raw: racadm vmdisconnect
      register: vmdisconnect
    - debug: var=vmdisconnect
    - name: getractime -- display the current RAC time 
      raw: racadm getractime -d
      register: ractime
    - debug: var=ractime
    - local_action: copy content={{ vmdisconnect.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/vmdisconnect/{{ inventory_hostname }}-vmdisconnect-{{ item }}.txt
      with_items: "{{ ractime.stdout_lines }}"
