--- # Testing
- hosts: idrac
  connection: ssh
  user: root
  sudo: yes
  gather_facts: no
  tasks:
    - name: vmdisconnect -- disconnect Virtual Media connections 
      raw: racadm vmdisconnect
      register: vmdisconnect
    - debug: var=vmdisconnect
    - local_action: copy content={{ vmdisconnect.stdout_lines }} dest=/root/ansible-idrac/auto-idrac/output/vmdisconnect/{{ inventory_hostname }}-vmdisconnect.txt
