---

- hosts: myhosts
  name: Add User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/myhosts

  tasks:

  # When adding a user, you must enable it afterwards
  - name: Add user
    local_action: >
       redfish category=Accounts command=AddUser baseuri={{baseuri}}
       user={{user}} password={{password}} userid={{userid}}
       username={{username}} userpswd={{userpswd}} userrole={{userrole}}

  - name: Enable user
    local_action: >
       redfish category=Accounts command=EnableUser baseuri={{baseuri}}
       user={{user}} password={{password}} userid={{userid}}

