---

- hosts: myhosts
  name: Disable User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/myhosts

  - name: Disable user
    local_action: >
       redfish category=Accounts command=DisableUser baseuri={{baseuri}}
       user={{user}} password={{password}} userid={{userid}}
