---

- hosts: myhosts
  name: Update user password
  gather_facts: False

  - name: Update user password
    local_action: >
       redfish category=Accounts command=UpdateUserPassword baseuri={{baseuri}}
       user={{user}} password={{password}} userid={{userid}}
       userpswd={{userpswd}}
