---

- hosts: myhosts
  name: Update user role
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/myhosts

  tasks:

  - name: Update user role
    local_action: >
       redfish category=Accounts command=UpdateUserRole baseuri={{baseuri}}
       user={{user}} password={{password}} userid={{userid}}
       userrole={{userrole}}
