---

- hosts: myhosts
  name: Get Manager attributes
  gather_facts: False

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml type=ManagerAttributes

  - name: Get Manager attributes
    local_action: >
       redfish category=Manager command=GetAttributes baseuri={{baseuri}}
       user={{user}} password={{password}}
    register: result
    ignore_errors: yes

  - name: Copy manager attributes to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
