---

- hosts: myhosts
  name: Set Mananger timezone
  gather_facts: False

  tasks:

  - name: Set Timezone
    local_action: >
       redfish category=Manager command=SetAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       mgr_attr_name=Time.1.Timezone mgr_attr_value={{timezone}}
    ignore_errors: yes
