---

- hosts: myhosts
  name: Set Manager NTP settings
  gather_facts: False

  tasks:

  - name: Enable NTP
    local_action: >
       redfish category=Manager command=SetAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       mgr_attr_name=NTPConfigGroup.1.NTPEnable mgr_attr_value=Enabled
    ignore_errors: yes

  - name: Set NTP server 1
    local_action: >
       redfish category=Manager command=SetAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       mgr_attr_name=NTPConfigGroup.1.NTP1 mgr_attr_value={{ntpserver1}}
    ignore_errors: yes

  # Add more NTP servers as needed
  # To get exact attributes names, run the getattributes task first

